[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "chess"
version = "0.1.0"
description = "chess library"
authors = [{ name = "Adam Alobousi" }]
dependencies = []